port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: false
  ipv6: false

rule-providers:
#广告域名列表
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

#局域网 IP 及保留 IP 地址列表
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - RULE-SET,reject,REJECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,自动选择

proxies:

proxy-groups:
  - name: 自动选择
    interval: 300
    type: select
    url: http://www.gstatic.com/generate_204
    proxies: